version: '3.0'
services:
  api:
    container_name: brazilian-worker.api
    build: api/
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - "./api:/home/api"
    tty: true
    stdin_open: true

  web:
    container_name: brazilian-worker.web
    build: web/
    ports:
      - "4200:4200"
    volumes:
        - "/app/node_modules"
        - "./web:/app"
